name: "Run update scripts"
on:
  schedule:
    # every day at 3:12am UTC, saving server costs as it is not a "round" time!
    - cron: '12 3 * * *'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: >
        cd packages/hytale-downloader
        bash update.sh

    - name: Commit and push
      uses: EndBug/add-and-commit@v9
      with:
        author_name: github-actions[bot]
        author_email: github-actions[bot]@users.noreply.github.com
        message: "update package hashes"
        add: "."
